[package]
name = "mdc24"
version = "0.1.1"
authors = ["Nick Shtansky"]
description = "A simple test of wasm performance"
license = "Unlicense"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
